galaxy_info:
  author: zmird
  description: Install and configure MAAS virtual lab.
  company: freesoftware
  license: MIT
  min_ansible_version: 2.1
  platforms:
  - name: Archlinux
    versions:
    - all
  galaxy_tags: []

dependencies: []
